# Generated by Django 5.0.1 on 2024-01-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='record',
            name='profile_iamge',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
