# Generated by Django 5.0.1 on 2024-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezapp', '0002_remove_record_city_remove_record_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='val',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.CharField(max_length=10)),
            ],
        ),
    ]
